txgh:
    github:
        repos:
            txgh-bot/txgh-test-resources:
                api_username: txgh-bot
                api_token: 034560878982f3ba339950af0c8de7a8a617c57b
                push_source_to: test-project-88
                branch: master
    transifex:
        projects:
            test-project-88:
                tx_config: ./config/tx.config
                api_username: txgh.bot
                api_password: 2aqFGW99fPRKWvXBPjbrxkdiR
                push_translations_to: txgh-bot/txgh-test-resources
